### ISSUE TITLE
Would PUFFIN score be accessible to parties in client auction?

### ISSUE THREAD

**Issue by brodrigu** [dmarti/PUFFIN#3]
Would the buyers bidding function or publishers scoring function be aware of the PUFFIN score within the private auction?

**Comment by dmarti** [comment]
For the buyer's bidding function, it seems like this would give out too much information: whether the function is bidding on a high-PUFFIN or low-PUFFIN subset of the interest group. It could encourage sites to add too many marginal people to the interest group and then rely on PUFFIN to only bid on some of them.

**Comment by dmarti** [comment]
Added to [FAQ](https://github.com/dmarti/PUFFIN/blob/main/FAQ.md), closing.
